#!/bin/bash

../../build/tracking_parser `cat ../file_prismi.txt` -o gnuplot_prismi -s MODE_CONSTR_COMPLEMENTARY_RO,PARAM_ROTATION_LIMIT  -s MODE_CONSTR_COMPLEMENTARY_TO,PARAM_TRANSLATION_LIMIT -s MODE_CONSTR_COMPLEMENTARY_TO,PARAM_TRANSLATION_DYN_LIMIT -s MODE_CONSTR_COMPLEMENTARY_RO,PARAM_ROTATION_DYN_LIMIT  -s MODE_CONSTR_COMPLEMENTARY_RO,PARAM_ROTATION_CURV_LIMIT -s MODE_OCULUS_FIRST,PARAM_NONE -s MODE_MOTIVE_FIRST,PARAM_NONE
../../build/tracking_parser `cat ../file_cubi.txt` -o gnuplot_cubi -s MODE_CONSTR_COMPLEMENTARY_RO,PARAM_ROTATION_LIMIT  -s MODE_CONSTR_COMPLEMENTARY_TO,PARAM_TRANSLATION_LIMIT -s MODE_CONSTR_COMPLEMENTARY_TO,PARAM_TRANSLATION_DYN_LIMIT -s MODE_CONSTR_COMPLEMENTARY_RO,PARAM_ROTATION_DYN_LIMIT  -s MODE_CONSTR_COMPLEMENTARY_RO,PARAM_ROTATION_CURV_LIMIT -s MODE_OCULUS_FIRST,PARAM_NONE -s MODE_MOTIVE_FIRST,PARAM_NONE

../../build/tracking_parser `cat ../file_prismi_alpha.txt` -o gnuplot_prismi -s MODE_COMPLEMENTARY,PARAM_ALPHA
../../build/tracking_parser `cat ../file_cubi_alpha.txt` -o gnuplot_cubi -s MODE_COMPLEMENTARY,PARAM_ALPHA

../../build/tracking_parser `cat ../file_prismi_short2.txt` -o gnuplot_prismi -s MODE_DIRECTED_COMPLEMENTARY,PARAM_ROTATION_DYN2_LIMIT  -s MODE_DIRECTED_COMPLEMENTARY,PARAM_ROTATION_CURV2_LIMIT -s MODE_DIRECTED_COMPLEMENTARY,PARAM_TRANSLATION_DYN2_LIMIT
../../build/tracking_parser `cat ../file_cubi_short2.txt` -o gnuplot_cubi -s MODE_DIRECTED_COMPLEMENTARY,PARAM_ROTATION_DYN2_LIMIT  -s MODE_DIRECTED_COMPLEMENTARY,PARAM_ROTATION_CURV2_LIMIT -s MODE_DIRECTED_COMPLEMENTARY,PARAM_TRANSLATION_DYN2_LIMIT
